# Generated by Django 3.1.2 on 2020-10-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='imgUrl',
        ),
        migrations.AddField(
            model_name='ad',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
