# Generated by Django 3.1.2 on 2020-10-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_auto_20201013_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='link',
            field=models.URLField(),
        ),
    ]
