# Generated by Django 3.1.2 on 2020-10-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0005_advertiser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='user',
        ),
    ]
